### ISSUE TITLE
Update README.md to Standard format

### ISSUE THREAD

**Issue by sbshah97** [salman-bhai/Competitive-Coding#2]
Ground rules:
1. Whoever claims the Issue first, **should** send a Pull Request within 24 hours else it'll be assigned to another claimant and further Pull Requests regarding that issue will not be entertained.
2. Pull Requests sent without **claiming** and referencing the Issue will not be entertained.
3. Make sure your Pull Requests have just one commit in them. **Squash** multiple commits into one if you have to.

Check out this [link](https://github.com/salman-bhai/E-Manager/blob/master/README.md) to understand better.

**Comment by MAPReiff** [comment]
I'll try it. What needs to be in it?

**Comment by sbshah97** [comment]
Click on the link in the description to take a look.

**Comment by richa-coder** [comment]
i have updated the readme file,please have a look.
Contains Solutions to Classic Problems of https://www.hackerrank.com/ (hackerrank) and https://www.hackerearth.com (hackerearth). The Solutions are written in C/C++.

**Comment by sbshah97** [comment]
@richa-coder Kindly send me a Pull Request as well!

**Comment by sbshah97** [comment]
@CoolComixs haven't received your Pull Request!

**Comment by richa-coder** [comment]
i have sent

[image: --]

Richa Singh
[image: https://]about.me/richa-singh
https://about.me/richa-singh?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links
